# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@prod:
    framework:
        # https://symfony.com/doc/5.4/http_cache.html#symfony-reverse-proxy
        http_cache: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
