presta_sitemap:
    defaults:
        # priority: 1
        changefreq: monthly
        # lastmod: now
    alternate:
        enabled: true
        default_locale: '%app.default_locale%'
        locales: '%app.supported_locales%'
        i18n: symfony