framework:
    default_locale: en
    # JMS\TranslationBundle\JMSTranslationBundle needs validation
    validation: ~
    translator:
        fallbacks:
            - en
        default_path: '%kernel.project_dir%/translations'
