framework:
    default_locale: '%app.default_locale%'
    # JMS\TranslationBundle\JMSTranslationBundle needs validation
    validation: ~
    translator:
        default_path: '%kernel.project_dir%/translations'
        # providers:
